name: "GitHub Kanban"
description: "Generates a static HTML page for your GitHub project"
author: "Serchinastico"

branding:
  icon: "map"
  color: "yellow"

inputs:
  project-url:
    description: "The URL of the project you want to clone"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
