name: "GitHub Kanban"
description: "Generates a static HTML page for your GitHub project"
author: "Serchinastico"

branding:
  icon: "map"
  color: "yellow"

inputs:
  token:
    description: "A personal access token with access to project, read:user and repo permissions"
    required: true
  project-url:
    description: "The URL of the project you want to clone"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
